=== darkone0112/DAM1/marcas/amistad.dtd
<!ELEMENT amistad (equipo1,equipo2)>
<!ELEMENT equipo1 (futbol,baloncesto,balonmano)>
<!ELEMENT equipo2 (futbol,baloncesto,balonmano)>
<!ELEMENT futbol (entrenadores,jugadores)>
<!ELEMENT baloncesto (entrenadores,jugadores)>
<!ELEMENT balonmano (entrenadores,jugadores)>
<!ELEMENT entrenadores (nombre,direccion,localidad,cp)>
<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador (nombre,direccion,localidad,cp)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ATTLIST entrenadores dni ID #REQUIRED>
<!ATTLIST entrenadores telefono CDATA #IMPLIED>

=== darkone0112/DAM1/marcas/amistad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amistad SYSTEM "amistad.dtd">
<amistad>
    <equipo1>
        <futbol>
            <entrenadores dni="y6066751d" telefono="">
                <nombre>q</nombre>
                <direccion></direccion>
                <localidad></localidad>
                <cp></cp>
            </entrenadores>
            <jugadores>
                <jugador>
                    <nombre></nombre>
                    <direccion></direccion>
                    <localidad></localidad>
                    <cp></cp>
                </jugador>
            </jugadores>
        </futbol>
        <baloncesto>
            <entrenadores dni="y6066751e" telefono="">
                <nombre></nombre>
                <direccion></direccion>
                <localidad></localidad>
                <cp></cp>
            </entrenadores>
            <jugadores>
                <jugador>
                    <nombre></nombre>
                    <direccion></direccion>
                    <localidad></localidad>
                    <cp></cp>
                </jugador>
            </jugadores>
        </baloncesto>
        <balonmano>
            <entrenadores dni="y5055141a" telefono="">
                <nombre></nombre>
                <direccion></direccion>
                <localidad></localidad>
                <cp></cp>
            </entrenadores>
            <jugadores>
                <jugador>
                    <nombre></nombre>
                    <direccion></direccion>
                    <localidad></localidad>
                    <cp></cp>
                </jugador>
            </jugadores>
        </balonmano>
    </equipo1>
    <equipo2>
        <futbol>
            <entrenadores dni="aaaa" telefono="">
                <nombre></nombre>
                <direccion></direccion>
                <localidad></localidad>
                <cp></cp>
            </entrenadores>
            <jugadores>
                <jugador>
                    <nombre></nombre>
                    <direccion></direccion>
                    <localidad></localidad>
                    <cp></cp>
                </jugador>
            </jugadores>
        </futbol>
        <baloncesto>
            <entrenadores dni="ss2222" telefono="">
                <nombre></nombre>
                <direccion></direccion>
                <localidad></localidad>
                <cp></cp>
            </entrenadores>
            <jugadores>
                <jugador>
                    <nombre></nombre>
                    <direccion></direccion>
                    <localidad></localidad>
                    <cp></cp>
                </jugador>
            </jugadores>
        </baloncesto>
        <balonmano>
            <entrenadores dni="a32" telefono="">
                <nombre></nombre>
                <direccion></direccion>
                <localidad></localidad>
                <cp></cp>
            </entrenadores>
            <jugadores>
                <jugador>
                    <nombre></nombre>
                    <direccion></direccion>
                    <localidad></localidad>
                    <cp></cp>
                </jugador>
            </jugadores>
        </balonmano>
    </equipo2>
</amistad>
