=== darkone0112/DAM1/marcas/jerarquia.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT persona (nombre,nacimiento,direccion)>
<!ELEMENT direccion (calle,poblacion,provincia,cpostal)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>
<!ATTLIST persona sexo (femenino|masculino) #REQUIRED>
<!ATTLIST nacimiento dia CDATA #REQUIRED>
<!ATTLIST nacimiento mes CDATA #REQUIRED>
<!ATTLIST nacimiento anio CDATA #REQUIRED>

=== darkone0112/DAM1/marcas/jerarquia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persona SYSTEM "jerarquia.dtd">
    <persona sexo="masculino">
        <nombre>Juan Pardo</nombre>
        <nacimiento dia = "10" mes="abril" anio="1982"></nacimiento>
        <direccion>
            <calle>caoba,1</calle>
            <poblacion>Madrid</poblacion>
            <provincia>Madrid</provincia>
            <cpostal>28005</cpostal>
        </direccion>
    </persona>
