=== darkone0112/DAM1/marcas/libros.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT libros (libro1,libro2,libro3,libro4,libro5)>
<!ELEMENT libro1 (titulo1,precio1)>
<!ATTLIST libro1 isbn CDATA #REQUIRED>
<!ELEMENT titulo1 (#PCDATA)>
<!ELEMENT precio1 (#PCDATA)>

<!ELEMENT libro2 (titulo2,autores,precio2)>
<!ATTLIST libro2 isbn CDATA #REQUIRED>
<!ELEMENT titulo2 (#PCDATA)>
<!ELEMENT autores (autor1,autor2)>
<!ELEMENT autor1 (#PCDATA)>
<!ELEMENT autor2 (#PCDATA)>
<!ELEMENT precio2 (#PCDATA)>

<!ELEMENT libro3 (titulo3,autor3,precio3)>
<!ATTLIST libro3 isbn CDATA #REQUIRED>
<!ELEMENT titulo3 (#PCDATA)>
<!ELEMENT autor3 (#PCDATA)>
<!ELEMENT precio3 EMPTY>

<!ELEMENT libro4 (titulo4,autor4,precios)>
<!ATTLIST libro4 isbn CDATA #REQUIRED>
<!ELEMENT titulo4 (#PCDATA)>
<!ELEMENT autor4 (#PCDATA)>
<!ELEMENT precios (precios1,precios2)>
<!ELEMENT precios1 (#PCDATA)>
<!ELEMENT precios2 (#PCDATA)>

<!ELEMENT libro5 (titulo5,autor5,precio5)>
<!ATTLIST libro5 isbn CDATA #REQUIRED>
<!ELEMENT titulo5 (#PCDATA)>
<!ELEMENT autor5 (#PCDATA)>
<!ELEMENT precio5 (#PCDATA)>

=== darkone0112/DAM1/marcas/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros SYSTEM "libros.dtd">
<libros>
    <libro1 isbn="">
        <titulo1></titulo1>
        <precio1></precio1>
    </libro1>
    <libro2 isbn="">
        <titulo2></titulo2>
        <autores>
            <autor1></autor1>
            <autor2></autor2>
        </autores>
        <precio2></precio2>
    </libro2>
    <libro3 isbn="">
        <titulo3></titulo3>
        <autor3></autor3>
        <precio3></precio3>
    </libro3>
    <libro4 isbn="">
        <titulo4></titulo4>
        <autor4></autor4>
        <precios>
            <precios1></precios1>
            <precios2></precios2>
        </precios>
    </libro4>
    <libro5 isbn="">
        <titulo5></titulo5>
        <autor5></autor5>
        <precio5></precio5>
    </libro5>
</libros>
