=== darkone0112/DAM1/marcas/libros1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT libros1 (libro+)>
<!ELEMENT libro (titulo,autores,editorial,revisores)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (nombre,apellidos,email)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT editorial (nombre,oficina,pagina)>
<!ELEMENT oficina (#PCDATA)>
<!ELEMENT pagina (#PCDATA)>
<!ELEMENT revisores (revisor)>
<!ELEMENT revisor (nombre,puntuacion,comentario)>
<!ELEMENT puntuacion (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>
<!ATTLIST libro isbn ID #REQUIRED>

=== darkone0112/DAM1/marcas/libros1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros1 SYSTEM "libros1.dtd">
<libros1>
    <libro isbn = "aaaaa">
        <titulo></titulo>
        <autores>
            <autor>
                <nombre></nombre>
                <apellidos></apellidos>
                <email></email>
            </autor>
        </autores>
        <editorial>
            <nombre></nombre>
            <oficina></oficina>
            <pagina></pagina>
        </editorial>
        <revisores>
            <revisor>
                <nombre></nombre>
                <puntuacion></puntuacion>
                <comentario></comentario>
            </revisor>
        </revisores>
    </libro>
</libros1>
