=== darkone0112/DAM1/marcas/pedidos.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pedidos (destino,ordenante,observaciones,productos)>
<!ELEMENT destino (ciudad,direccion,nombre,codpostal)>
<!ELEMENT ordenante (nombre,ciudad,direccion,codpostal)>
<!ELEMENT productos (producto+)>
<!ELEMENT producto (nombre,cantidad,observaciones?,precio)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT codpostal (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

<!ATTLIST pedidos fecha CDATA #REQUIRED>
<!ATTLIST producto tipo (electrica|gasolina|nodefinido) #REQUIRED>
<!ATTLIST producto codigo CDATA #REQUIRED>

=== darkone0112/DAM1/marcas/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "pedidos.dtd">
<pedidos fecha="20/10/99">
    <destino>
        <ciudad>Albacete</ciudad>
        <direccion>Plaza de la Duquesa 12</direccion>
        <nombre>Alicia Abad</nombre>
        <codpostal>05020</codpostal>
    </destino>
    <ordenante>
        <nombre>Roberto Movilla</nombre>
        <ciudad>Madrid</ciudad>
        <direccion>General Ricardos 56</direccion>
        <codpostal>28055</codpostal>
    </ordenante>
    <observaciones>Es urgente</observaciones>
    <productos>
        <producto tipo="electrica" codigo="872-AA">
            <nombre>Cortadora de Cesped</nombre>
            <cantidad>1</cantidad>
            <observaciones>Que sea electrica</observaciones>
            <precio>148,95 euros</precio>
        </producto>
        <producto tipo="nodefinido" codigo="926-FH">
            <nombre>Podadoras de Cesped</nombre>
            <cantidad>3</cantidad>
            <observaciones>No esta definido</observaciones>
            <precio>7,98 euros</precio>
        </producto>
    </productos>
</pedidos>
