=== darkone0112/DAM1/marcas/prueba.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT clase (alumno, alumno, alumno)>
<!ELEMENT alumno (nombre,apellido1,apellido2?,telefono)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono tipo (fijo | movil) #REQUIRED>

=== darkone0112/DAM1/marcas/prueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clase SYSTEM "prueba.dtd">

<clase>
    <alumno>
        <nombre></nombre>
        <apellido1></apellido1>
        <apellido2></apellido2>
        <telefono tipo="fijo"></telefono>
    </alumno>
    <alumno>
        <nombre></nombre>
        <apellido1></apellido1>
        <apellido2></apellido2>
        <telefono tipo="movil"></telefono>
    </alumno>
    <alumno>
        <nombre></nombre>
        <apellido1></apellido1>
        <apellido2></apellido2>
        <telefono tipo="fijo"></telefono>
    </alumno>
</clase>
