=== darkone0112/DAM1/marcas/songs.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cd (fecha,songs+)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT songs (song+)>
<!ELEMENT song (titulo,compositores,productores,publisher,artistas)>
<!ELEMENT compositores (compositor)>
<!ELEMENT compositor (nombre,apellido)>
<!ELEMENT productores (productor)>
<!ELEMENT productor (nombre,apellido)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT artistas (artista)>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ATTLIST cd titulo CDATA #REQUIRED>
<!ATTLIST song duracion CDATA #IMPLIED>
<!ATTLIST fecha dia CDATA #REQUIRED>
<!ATTLIST fecha mes CDATA #REQUIRED>
<!ATTLIST fecha anio CDATA #REQUIRED>
<!ATTLIST song anio CDATA #IMPLIED>

=== darkone0112/DAM1/marcas/song.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cd SYSTEM "songs.dtd">
<cd titulo="">
<fecha dia="a" mes="a" anio="a"></fecha>
    <songs>
        <song duracion="3:20" anio="1978">
            <titulo></titulo>
            <compositores>
                <compositor>
                    <nombre></nombre>
                    <apellido></apellido>
                </compositor>
            </compositores>
            <productores>
                <productor>
                    <nombre></nombre>
                    <apellido></apellido>
                </productor>
            </productores>
            <publisher></publisher>
            <artistas>
                <artista></artista>
            </artistas>
        </song>
    </songs>
</cd>
